# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\WinAuto\Automation\QTDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1028, 567)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(800, 460, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(61, 51, 731, 391))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_3.setMaximum(2999)
        self.horizontalSlider_3.setProperty("value", 0)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout.addWidget(self.horizontalSlider_3)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setMaximum(2999)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_6.setMaximum(2999)
        self.horizontalSlider_6.setProperty("value", 0)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.verticalLayout.addWidget(self.horizontalSlider_6)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_5.setMaximum(2999)
        self.horizontalSlider_5.setProperty("value", 0)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.verticalLayout.addWidget(self.horizontalSlider_5)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_4.setMaximum(2999)
        self.horizontalSlider_4.setProperty("value", 0)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.verticalLayout.addWidget(self.horizontalSlider_4)
        self.horizontalSlider_7 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_7.setMaximum(2999)
        self.horizontalSlider_7.setProperty("value", 0)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.verticalLayout.addWidget(self.horizontalSlider_7)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_2.setMaximum(2999)
        self.horizontalSlider_2.setProperty("value", 0)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout.addWidget(self.horizontalSlider_2)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(800, 60, 121, 381))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_2.addWidget(self.lineEdit_7)

        self.retranslateUi(Dialog)
        self.horizontalSlider_3.valueChanged['int'].connect(self.Slider3changeEdit)
        self.lineEdit.editingFinished.connect(self.EditchangeSlider3)
        self.horizontalSlider.valueChanged['int'].connect(self.SliderchangeEdit2)
        self.lineEdit_2.editingFinished.connect(self.Edit2changeSlider)
        self.horizontalSlider_6.valueChanged['int'].connect(self.Slider6changeEdit3)
        self.lineEdit_3.editingFinished.connect(self.Edit3changeSlider6)
        self.horizontalSlider_5.valueChanged['int'].connect(self.Slider5changeEdit4)
        self.lineEdit_4.editingFinished.connect(self.Edit4changeSlider5)
        self.horizontalSlider_4.valueChanged['int'].connect(self.Slider4changeEdit5)
        self.lineEdit_5.editingFinished.connect(self.Edit5changeSlider4)
        self.horizontalSlider_7.valueChanged['int'].connect(self.Slider7changeEdit6)
        self.lineEdit_6.editingFinished.connect(self.Edit6changeSlider7)
        self.horizontalSlider_2.valueChanged['int'].connect(self.Slider2changeEdit7)
        self.lineEdit_7.editingFinished.connect(self.Edit7changeSlider2)
        # QtCore.QMetaObject.connectSlotsByName(Dialog)
    def Slider3changeEdit(self, position):
        self.lineEdit.setText(str(position/100.0))
    def EditchangeSlider3(self):
        fval = float(self.lineEdit.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider_3.setValue(int(fval))
    def SliderchangeEdit2(self, position):
        self.lineEdit_2.setText(str(position/100.0))
    def Edit2changeSlider(self):
        fval = float(self.lineEdit_2.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider.setValue(int(fval))
    def Slider6changeEdit3(self, position):
        self.lineEdit_3.setText(str(position/100.0))
    def Edit3changeSlider6(self):
        fval = float(self.lineEdit_3.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider_6.setValue(int(fval))
    def Slider5changeEdit4(self, position):
        self.lineEdit_4.setText(str(position/100.0))
    def Edit4changeSlider5(self):
        fval = float(self.lineEdit_4.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider_5.setValue(int(fval))
    def Slider4changeEdit5(self, position):
        self.lineEdit_5.setText(str(position/100.0))
    def Edit5changeSlider4(self):
        fval = float(self.lineEdit_5.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider_4.setValue(int(fval))
    def Slider7changeEdit6(self, position):
        self.lineEdit_6.setText(str(position/100.0))
    def Edit6changeSlider7(self):
        fval = float(self.lineEdit_6.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider_7.setValue(int(fval))
    def Slider2changeEdit7(self, position):
        self.lineEdit_7.setText(str(position/100.0))
    def Edit7changeSlider2(self):
        fval = float(self.lineEdit_7.text())*100 
        fval = fval if fval <= 2999 else 2999
        fval = fval if fval >=0 else 0
        self.horizontalSlider_2.setValue(int(fval))
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "INIT"))
        self.lineEdit.setText(_translate("Dialog", "0.00"))
        self.lineEdit_2.setText(_translate("Dialog", "0.00"))
        self.lineEdit_3.setText(_translate("Dialog", "0.00"))
        self.lineEdit_4.setText(_translate("Dialog", "0.00"))
        self.lineEdit_5.setText(_translate("Dialog", "0.00"))
        self.lineEdit_6.setText(_translate("Dialog", "0.00"))
        self.lineEdit_7.setText(_translate("Dialog", "0.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
